<?xml version="1.0" encoding="utf-8"?>
<Application>
  <ModelsRepository>
    <Models/>
  </ModelsRepository>
  <DataSourceRepository/>
  <Header>
    <Version val="12050"/>
    <APPLICATION val="Y"/>
    <WithIsn val="N"/>
    <Exe/>
    <_InternalTask/>
    <IsRoot/>
    <InIndex/>
    <WITH_MODELS/>
    <MAIN_PRG_VARS val="0"/>
    <MAIN_PRG_DSPS val="1"/>
    <Arguments END="2" START="2"/>
  </Header>
  <ProgramsRepository>
    <Programs>
      <Task>
        <Header Description="map_1_5_1">
          <Public val="map_1_5_1"/>
          <ExecutionRight/>
          <Resident val="N"/>
          <SQL val="N"/>
          <ReturnValue>
            <ReturnValueAttr/>
            <ParametersAttributes/>
          </ReturnValue>
          <SqlWhereExist val="N"/>
          <TaskType val="B"/>
          <External val="Y"/>
          <LastModified _date="738365" _time="54621" date="29//7//2022" time="15:10:21.7049702"/>
        </Header>
        <ReturnValueExpression/>
        <Resource/>
        <Information>
          <Key>
            <Column/>
            <Mode val="N"/>
          </Key>
          <DB/>
          <Sort>
            <CLS val="A"/>
          </Sort>
          <ForceRecordDelete DEL="N"/>
          <EndTaskCondition val="Y"/>
          <EvaluateEndCondition val="A"/>
          <InitialMode val="M"/>
          <Locate Direction="A"/>
          <Range Direction="A"/>
          <VarRange/>
          <TaskProperties>
            <SelectionTable val="N"/>
            <ConfirmUpdate CNFU="N"/>
            <ConfirmCancel val="N"/>
            <ErrorStrategy val="R"/>
            <LockingStrategy val="M"/>
            <CacheStrategy val="T"/>
            <ForceRecordSuffix val="N"/>
            <TransactionMode val="P"/>
            <TransactionBegin val="N"/>
            <PreloadView val="N"/>
            <KeepCreatedContext val="N"/>
          </TaskProperties>
          <SIDE_WIN>
            <AllowOptions val="N"/>
            <AllowQuery val="Y"/>
            <AllowModify val="Y"/>
            <AllowCreate val="Y"/>
            <AllowDelete val="Y"/>
            <AllowLocate val="Y"/>
            <AllowRange val="Y"/>
            <AllowIndexChange val="Y"/>
            <AllowSorting val="Y"/>
            <AllowIOFiles val="Y"/>
            <RecordCycle val="Y"/>
            <AllowEvents val="Y"/>
            <AllowIndexOptimization val="Y"/>
            <AllowLocationInQuery val="Y"/>
            <AllowPrintingData val="N"/>
          </SIDE_WIN>
          <WIN>
            <OpenTaskWindow val="N"/>
            <CloseTaskWindow val="Y"/>
            <ForegroundWindow val="Y"/>
            <FlipFld val="N"/>
            <RefreshTaskWindow ReturnValue="N"/>
          </WIN>
          <BOX>
            <Direction val="V"/>
          </BOX>
        </Information>
        <TaskLogic>
          <LogicUnit id="4" propagate="78">
            <Level val="R"/>
            <Type val="M"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
            <LogicLines>
              <LogicLine>
                <DATAVIEW_SRC Type="M">
                  <Condition val="N"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </DATAVIEW_SRC>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="0"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
            </LogicLines>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="R"/>
            <Type val="S"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
            <LogicLines>
              <LogicLine>
                <Evaluate>
                  <Expression val="1"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="********  BeginTask-1********"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=" Before CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="******** Begin Iniput of schema ********"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="2"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="******** End Iniput of schema ********"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="P"/>
                    <Exp val="4"/>
                    <PublicObject/>
                  </Event>
                  <Wait val="89"/>
                  <Arguments>
                    <Argument>
                      <id val="0"/>
                      <Expression val="5"/>
                      <Skip val="N"/>
                    </Argument>
                  </Arguments>
                  <Condition Exp="3"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="6"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="7"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="P"/>
                    <Exp val="9"/>
                    <PublicObject/>
                  </Event>
                  <Wait val="89"/>
                  <Arguments>
                    <Argument>
                      <id val="0"/>
                      <Expression val="10"/>
                      <Skip val="N"/>
                    </Argument>
                  </Arguments>
                  <Condition Exp="8"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="12"/>
                  <ReturnValue/>
                  <Condition Exp="11"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="13"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <CallTask>
                  <OperationType val="T"/>
                  <TaskID comp="-1" obj="1"/>
                  <Lock val="N"/>
                  <Arguments/>
                  <Wait val="Y"/>
                  <SyncData val="N"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </CallTask>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="14"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=" After CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="16"/>
                  <ReturnValue/>
                  <Condition Exp="15"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="17"/>
                  <ReturnValue/>
                  <Condition Exp="15"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="18"/>
                  <ReturnValue/>
                  <Condition Exp="15"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="P"/>
                    <Exp val="19"/>
                    <PublicObject/>
                  </Event>
                  <Wait val="89"/>
                  <Arguments>
                    <Argument>
                      <id val="0"/>
                      <Expression val="20"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="21"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Skip val="Y"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="22"/>
                      <Skip val="N"/>
                    </Argument>
                  </Arguments>
                  <Condition Exp="15"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="********  EndTask-1********"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="42"/>
                  <ReturnValue/>
                  <Condition Exp="41"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
            </LogicLines>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="R"/>
            <Type val="P"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="T"/>
            <Type val="P"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="T"/>
            <Type val="S"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="F"/>
            <Type val="U"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="I"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="F"/>
              <ErrorTrigger/>
              <PublicObject comp="-1"/>
            </Event>
            <TXT val="GetSqlStmt"/>
            <Expanded val="1"/>
            <LogicLines>
              <LogicLine>
                <Evaluate>
                  <Expression val="23"/>
                  <ReturnValue/>
                  <Condition Exp="24"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
            </LogicLines>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="H"/>
            <Type val="U"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="I"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="U"/>
              <ErrorTrigger/>
              <PublicObject comp="-1" obj="1"/>
            </Event>
            <Expanded val="1"/>
            <LogicLines>
              <LogicLine>
                <Evaluate>
                  <Expression val="26"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="P"/>
                    <Exp val="27"/>
                    <PublicObject/>
                  </Event>
                  <Wait val="89"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
            </LogicLines>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="H"/>
            <Type val="U"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="I"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="U"/>
              <ErrorTrigger/>
              <PublicObject comp="-1" obj="2"/>
            </Event>
            <Expanded val="1"/>
            <LogicLines>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="P"/>
                    <Exp val="28"/>
                    <PublicObject/>
                  </Event>
                  <Wait val="89"/>
                  <Arguments>
                    <Argument>
                      <id val="0"/>
                      <Expression val="29"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="30"/>
                      <Skip val="N"/>
                    </Argument>
                  </Arguments>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="31"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="32"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="U"/>
                    <PublicObject comp="-1" obj="1"/>
                  </Event>
                  <Wait val="89"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
            </LogicLines>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="H"/>
            <Type val="U"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="I"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="U"/>
              <ErrorTrigger/>
              <PublicObject comp="-1" obj="3"/>
            </Event>
            <Expanded val="1"/>
            <LogicLines>
              <LogicLine>
                <Evaluate>
                  <Expression val="33"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="U"/>
                    <PublicObject comp="-1" obj="2"/>
                  </Event>
                  <Wait val="89"/>
                  <Condition Exp="25"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
            </LogicLines>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="H"/>
            <Type val="U"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="I"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="R"/>
              <ErrorTrigger val="1"/>
              <PublicObject comp="-1" obj="-1"/>
            </Event>
            <Expanded val="1"/>
            <LogicLines>
              <LogicLine>
                <Evaluate>
                  <Expression val="34"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="23"/>
                  <ReturnValue/>
                  <Condition Exp="24"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="35"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="U"/>
                    <PublicObject comp="-1" obj="3"/>
                  </Event>
                  <Wait val="89"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
            </LogicLines>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="H"/>
            <Type val="U"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="I"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="R"/>
              <ErrorTrigger val="2"/>
              <PublicObject comp="-1" obj="-1"/>
            </Event>
            <Expanded val="1"/>
            <LogicLines>
              <LogicLine>
                <Evaluate>
                  <Expression val="34"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="23"/>
                  <ReturnValue/>
                  <Condition Exp="24"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="36"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="U"/>
                    <PublicObject comp="-1" obj="3"/>
                  </Event>
                  <Wait val="89"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
            </LogicLines>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="H"/>
            <Type val="U"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="I"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="R"/>
              <ErrorTrigger val="3"/>
              <PublicObject comp="-1" obj="-1"/>
            </Event>
            <Expanded val="1"/>
            <LogicLines>
              <LogicLine>
                <Evaluate>
                  <Expression val="34"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="23"/>
                  <ReturnValue/>
                  <Condition Exp="24"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="37"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="U"/>
                    <PublicObject comp="-1" obj="3"/>
                  </Event>
                  <Wait val="89"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
            </LogicLines>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="H"/>
            <Type val="U"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="I"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="R"/>
              <ErrorTrigger val="7"/>
              <PublicObject comp="-1" obj="-1"/>
            </Event>
            <Expanded val="1"/>
            <LogicLines>
              <LogicLine>
                <Evaluate>
                  <Expression val="34"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="23"/>
                  <ReturnValue/>
                  <Condition Exp="24"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="38"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="U"/>
                    <PublicObject comp="-1" obj="3"/>
                  </Event>
                  <Wait val="89"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
            </LogicLines>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="H"/>
            <Type val="U"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="I"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="R"/>
              <ErrorTrigger val="8"/>
              <PublicObject comp="-1" obj="-1"/>
            </Event>
            <Expanded val="1"/>
            <LogicLines>
              <LogicLine>
                <Evaluate>
                  <Expression val="34"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="23"/>
                  <ReturnValue/>
                  <Condition Exp="24"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="39"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="U"/>
                    <PublicObject comp="-1" obj="3"/>
                  </Event>
                  <Wait val="89"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
            </LogicLines>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="H"/>
            <Type val="U"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="I"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="U"/>
              <ErrorTrigger/>
              <PublicObject comp="-1" obj="4"/>
            </Event>
            <Expanded val="1"/>
            <LogicLines>
              <LogicLine>
                <Evaluate>
                  <Expression val="40"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
            </LogicLines>
          </LogicUnit>
        </TaskLogic>
        <TaskForms>
          <FormEntry _last_test_id="1">
            <PropertyList model="FORM_GUI0">
              <Width/>
              <Height/>
              <_Comment/>
              <FormName valUnicode="Empty Program"/>
            </PropertyList>
          </FormEntry>
        </TaskForms>
        <Expressions>
          <Expression val="1">
            <ExpSyntax val="SetParam('xmlErr',' ')"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="2">
            <ExpSyntax val="INIPut (TranslateNR('[MAGIC_DATABASES]SourceDB_1_5_1_1 =* DBMS,21, %MSSQL_db%, ,%MSSQL_server%,  ,%MSSQL_user%, '&amp;SharedValGet('IBMSSQL_pass')&amp;', NoMagicRecordLock, DontChangeFileInToolkit, NoCheckDefinition, NoCheckKey, NoFileLocks,  SQLBLOB=%sql_blobsize%, , NoCheckExist, 0, %MSSQL_db%, NoAS400SrvrSort,'),'FALSE'LOG)"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="3">
            <ExpSyntax val="SharedValGet('IBDebugMapper')='true'log"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="4">
            <ExpSyntax val="'MainWriteLog'"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="5">
            <ExpSyntax val="TranslateNR('SourceDB_1_5_1_1. Trying to connect, MS-SQL,DB=%MSSQL_db%,Server=%MSSQL_server%, User=%MSSQL_user%,Pass=**********')"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="6">
            <ExpSyntax val="setparam('IB_SqlDBName','SourceDB_1_5_1_1')"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="7">
            <ExpSyntax val="GetSqlStmt()"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="8">
            <ExpSyntax val="SharedValGet('IBDebugMapper')='true'log"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="9">
            <ExpSyntax val="'MainWriteLog'"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="10">
            <ExpSyntax val="getparam('IB_SqlStmt')"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="11">
            <ExpSyntax val="getParam('Error')&lt;&gt;0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="12">
            <ExpSyntax val="setparam('MapperLastErrorCode',getparam('Error'))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="13">
            <ExpSyntax val="setparam('Error',0)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="14">
            <ExpSyntax val="SetParam('xpi_SourceJsonIsNotWellFormed',NULL())"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="15">
            <ExpSyntax val="NOT(iBolt_FileExist (Trim(Flip(Del(Flip(TranslateNR(getFullPath(EnvVal ('currentprojectdir') &amp;'Output¥集計用データ出力.csv'))),1,InStr(Flip(TranslateNR(getFullPath(EnvVal ('currentprojectdir') &amp;'Output¥集計用データ出力.csv'))),trim(TranslateNR ('%sl%'))))))))"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="16">
            <ExpSyntax val="SetParam('Error',454)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="17">
            <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans ('Destination directory does not exist.'))"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="18">
            <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="19">
            <ExpSyntax val="'SaveInternalMSG'"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="20">
            <ExpSyntax val="15"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="21">
            <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="22">
            <ExpSyntax val="'txt'"/>
            <ExpAttribute val="T"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="23">
            <ExpSyntax val="SetParam('IB_SqlStmt',TranslateNR('SELECT [FINAL_RESULTS3].[nhk_upper_group_code],[FINAL_RESULTS3].[nhk_upper_group_name],[FINAL_RESULTS3].[month],[FINAL_RESULTS3].[dep_code],[FINAL_RESULTS3].[dep_name],[FINAL_RESULTS3].[pj_code],[FINAL_RESULTS3].[pj_name],[FINAL_RESULTS3].[type1_code],[FINAL_RESULTS3].[type1_name],[FINAL_RESULTS3].[type2_code],[FINAL_RESULTS3].[type2_name],COUNT( [FINAL_RESULTS3].[emp_code]) AS HEADCOUNT, ROUND(SUM([FINAL_RESULTS3].[work_time]),0) AS TOTAL_TIME FROM dbo.[FINAL_RESULTS3] GROUP BY [FINAL_RESULTS3].[nhk_upper_group_code],[FINAL_RESULTS3].[nhk_upper_group_name],[FINAL_RESULTS3].[dep_code],[FINAL_RESULTS3].[dep_name],[FINAL_RESULTS3].[month],[FINAL_RESULTS3].[pj_name],[FINAL_RESULTS3].[pj_code],[FINAL_RESULTS3].[type1_code],[FINAL_RESULTS3].[type1_name],[FINAL_RESULTS3].[type2_code],[FINAL_RESULTS3].[type2_name]'))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="24">
            <ExpSyntax val="GetParam('IB_SqlDBName')= 'SourceDB_1_5_1_1'"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="25">
            <ExpSyntax val="ErrDatabaseName ()= 'SourceDB_1_5_1_1'"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="26">
            <ExpSyntax val="SetParam('IB_SqlDBName',ErrDatabaseName())"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="27">
            <ExpSyntax val="'MainDBError'"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="28">
            <ExpSyntax val="'MainMap_InitiVars'"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="29">
            <ExpSyntax val="0"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="30">
            <ExpSyntax val="0"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="31">
            <ExpSyntax val="SetParam('ErrBPID',0)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="32">
            <ExpSyntax val="SetParam('ErrFlowID',0)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="33">
            <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans (ErrDbmsMessage ()))"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="34">
            <ExpSyntax val="SetParam('IB_SqlDBName',ErrDatabaseName())"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="35">
            <ExpSyntax val="SetParam('Error',9801)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="36">
            <ExpSyntax val="SetParam('Error',9802)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="37">
            <ExpSyntax val="SetParam('Error',9803)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="38">
            <ExpSyntax val="SetParam('Error',9804)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="39">
            <ExpSyntax val="SetParam('Error',9805)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="40">
            <ExpSyntax val="Rollback('FALSE'LOG,0)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="41">
            <ExpSyntax val="GetParam('xmlErr')&lt;&gt;''"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="42">
            <ExpSyntax val="SetParam('C.sys.LastErrorInfo',GetParam('xmlErr'))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
        </Expressions>
        <EVNT DESC="Errors" FORCE_EXIT="N" id="1">
          <Event>
            <EventType val="N"/>
            <PublicObject/>
          </Event>
        </EVNT>
        <EVNT DESC="Err_1" FORCE_EXIT="N" id="2">
          <Event>
            <EventType val="N"/>
            <PublicObject/>
          </Event>
        </EVNT>
        <EVNT DESC="EachError" FORCE_EXIT="N" id="3">
          <Event>
            <EventType val="N"/>
            <PublicObject/>
          </Event>
        </EVNT>
        <EVNT DESC="ibRollback" FORCE_EXIT="N" id="4">
          <Event>
            <EventType val="N"/>
            <PublicObject/>
          </Event>
        </EVNT>
        <Task>
          <Header Description="FlatFile_2">
            <Public/>
            <ExecutionRight/>
            <Resident val="N"/>
            <SQL val="Y"/>
            <ReturnValue>
              <ReturnValueAttr/>
              <ParametersAttributes/>
            </ReturnValue>
            <SqlWhereExist val="N"/>
            <TaskType val="B"/>
            <External val="Y"/>
            <LastModified _date="738365" _time="54621" date="29//7//2022" time="15:10:21.7199888"/>
          </Header>
          <ReturnValueExpression/>
          <Resource>
            <IO>
              <Description val="I/O-FlatFile_Write"/>
              <IOExpression val="53"/>
              <OpenPrintDialog val="N"/>
              <PaperSize val="68"/>
              <Format val="L"/>
              <Media val="T"/>
              <Access val="W"/>
              <Copies val="1"/>
              <Orientation val="P"/>
              <PrintPreview val="N"/>
              <Vis2LogTranslation val="N"/>
              <FlipLines val="N"/>
            </IO>
            <Columns>
              <Column id="1" name="S_1_&quot;nhk_upper_group_code&quot;">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_ALPHA"/>
                  <NullAllowed val="Y"/>
                  <StoredAs val="3"/>
                  <Size/>
                  <_FieldStyle val="1"/>
                  <Type val="CHAR"/>
                  <Picture valUnicode="3"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
              <Column id="2" name="S_1_&quot;nhk_upper_group_name&quot;">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_UNICODE"/>
                  <NullAllowed val="Y"/>
                  <StoredAs val="32"/>
                  <Size/>
                  <_FieldStyle val="1"/>
                  <Type val="NVARCHAR"/>
                  <Picture valUnicode="20"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
              <Column id="3" name="S_1_&quot;month&quot;">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_ALPHA"/>
                  <NullAllowed val="Y"/>
                  <StoredAs val="3"/>
                  <Size/>
                  <_FieldStyle val="1"/>
                  <Type val="CHAR"/>
                  <Picture valUnicode="6"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
              <Column id="4" name="S_1_&quot;dep_code&quot;">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_ALPHA"/>
                  <NullAllowed val="Y"/>
                  <StoredAs val="3"/>
                  <Size/>
                  <_FieldStyle val="1"/>
                  <Type val="CHAR"/>
                  <Picture valUnicode="4"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
              <Column id="5" name="S_1_&quot;dep_name&quot;">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_UNICODE"/>
                  <NullAllowed val="Y"/>
                  <StoredAs val="32"/>
                  <Size/>
                  <_FieldStyle val="1"/>
                  <Type val="NVARCHAR"/>
                  <Picture valUnicode="30"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
              <Column id="6" name="S_1_&quot;pj_code&quot;">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_ALPHA"/>
                  <NullAllowed val="Y"/>
                  <StoredAs val="3"/>
                  <Size/>
                  <_FieldStyle val="1"/>
                  <Type val="CHAR"/>
                  <Picture valUnicode="5"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
              <Column id="7" name="S_1_&quot;pj_name&quot;">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_UNICODE"/>
                  <NullAllowed val="Y"/>
                  <StoredAs val="32"/>
                  <Size/>
                  <_FieldStyle val="1"/>
                  <Type val="NVARCHAR"/>
                  <Picture valUnicode="30"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
              <Column id="8" name="S_1_&quot;type1_code&quot;">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_ALPHA"/>
                  <NullAllowed val="Y"/>
                  <StoredAs val="3"/>
                  <Size/>
                  <_FieldStyle val="1"/>
                  <Type val="CHAR"/>
                  <Picture valUnicode="5"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
              <Column id="9" name="S_1_&quot;type1_name&quot;">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_UNICODE"/>
                  <NullAllowed val="Y"/>
                  <StoredAs val="32"/>
                  <Size/>
                  <_FieldStyle val="1"/>
                  <Type val="NVARCHAR"/>
                  <Picture valUnicode="20"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
              <Column id="10" name="S_1_&quot;type2_code&quot;">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_ALPHA"/>
                  <NullAllowed val="Y"/>
                  <StoredAs val="3"/>
                  <Size/>
                  <_FieldStyle val="1"/>
                  <Type val="CHAR"/>
                  <Picture valUnicode="5"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
              <Column id="11" name="S_1_&quot;type2_name&quot;">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_UNICODE"/>
                  <NullAllowed val="Y"/>
                  <StoredAs val="32"/>
                  <Size/>
                  <_FieldStyle val="1"/>
                  <Type val="NVARCHAR"/>
                  <Picture valUnicode="20"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
              <Column id="12" name="S_1_&quot;HEADCOUNT&quot;">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_NUMERIC"/>
                  <NullAllowed val="Y"/>
                  <StoredAs val="4"/>
                  <Size val="4"/>
                  <_Dec val="0"/>
                  <_Whole val="10"/>
                  <_Negative val="1"/>
                  <_FieldStyle val="1"/>
                  <Type val="INTEGER"/>
                  <Picture valUnicode="N10"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
              <Column id="13" name="S_1_&quot;TOTAL_TIME&quot;">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_NUMERIC"/>
                  <NullAllowed val="Y"/>
                  <StoredAs val="12"/>
                  <Size val="20"/>
                  <_Dec val="2"/>
                  <_Whole val="36"/>
                  <_Negative val="1"/>
                  <_FieldStyle val="1"/>
                  <Type val="NUMERIC"/>
                  <Picture valUnicode="N36.2"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
              <Column id="14" name="D_2_所属局コード">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_UNICODE"/>
                  <StoredAs val="32"/>
                  <Size val="60"/>
                  <_FieldStyle val="1"/>
                  <Picture valUnicode="30"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
              <Column id="15" name="D_2_所属局名称">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_UNICODE"/>
                  <StoredAs val="32"/>
                  <Size val="60"/>
                  <_FieldStyle val="1"/>
                  <Picture valUnicode="30"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
              <Column id="16" name="D_2_対象月">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_UNICODE"/>
                  <StoredAs val="32"/>
                  <Size val="60"/>
                  <_FieldStyle val="1"/>
                  <Picture valUnicode="30"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
              <Column id="17" name="D_2_業務実施部局コード">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_UNICODE"/>
                  <StoredAs val="32"/>
                  <Size val="60"/>
                  <_FieldStyle val="1"/>
                  <Picture valUnicode="30"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
              <Column id="18" name="D_2_業務実施部局名称">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_UNICODE"/>
                  <StoredAs val="32"/>
                  <Size val="60"/>
                  <_FieldStyle val="1"/>
                  <Picture valUnicode="30"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
              <Column id="19" name="D_2_プロジェクトコード">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_UNICODE"/>
                  <StoredAs val="32"/>
                  <Size val="60"/>
                  <_FieldStyle val="1"/>
                  <Picture valUnicode="30"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
              <Column id="20" name="D_2_プロジェクト名称">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_UNICODE"/>
                  <StoredAs val="32"/>
                  <Size val="60"/>
                  <_FieldStyle val="1"/>
                  <Picture valUnicode="30"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
              <Column id="21" name="D_2_第2階層コード">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_UNICODE"/>
                  <StoredAs val="32"/>
                  <Size val="60"/>
                  <_FieldStyle val="1"/>
                  <Picture valUnicode="30"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
              <Column id="22" name="D_2_第2階層名称">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_UNICODE"/>
                  <StoredAs val="32"/>
                  <Size val="60"/>
                  <_FieldStyle val="1"/>
                  <Picture valUnicode="30"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
              <Column id="23" name="D_2_第3階層コード">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_UNICODE"/>
                  <StoredAs val="32"/>
                  <Size val="60"/>
                  <_FieldStyle val="1"/>
                  <Picture valUnicode="30"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
              <Column id="24" name="D_2_第3階層名称">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_UNICODE"/>
                  <StoredAs val="32"/>
                  <Size val="60"/>
                  <_FieldStyle val="1"/>
                  <Picture valUnicode="30"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
              <Column id="25" name="D_2_人数">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_NUMERIC"/>
                  <StoredAs val="6"/>
                  <Size val="8"/>
                  <_Dec val="0"/>
                  <_Whole val="12"/>
                  <_Negative val="0"/>
                  <_FieldStyle val="1"/>
                  <Picture valUnicode="12"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
              <Column id="26" name="D_2_時間">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_NUMERIC"/>
                  <StoredAs val="6"/>
                  <Size val="8"/>
                  <_Dec val="00"/>
                  <_Whole val="12"/>
                  <_Negative val="0"/>
                  <_FieldStyle val="1"/>
                  <Picture valUnicode="12.00"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
            </Columns>
          </Resource>
          <Information>
            <Key>
              <Column/>
              <Mode val="N"/>
            </Key>
            <DB/>
            <Sort>
              <CLS val="A"/>
            </Sort>
            <ForceRecordDelete DEL="N"/>
            <EndTaskCondition val="Y" Exp="1"/>
            <EvaluateEndCondition val="A"/>
            <InitialMode val="M"/>
            <Locate Direction="A"/>
            <Range Direction="A"/>
            <VarRange/>
            <TaskProperties>
              <SelectionTable val="N"/>
              <ConfirmUpdate CNFU="N"/>
              <ConfirmCancel val="N"/>
              <ErrorStrategy val="R"/>
              <LockingStrategy val="M"/>
              <CacheStrategy val="T"/>
              <ForceRecordSuffix val="N"/>
              <TransactionMode val="P"/>
              <TransactionBegin val="N"/>
              <PreloadView val="N"/>
              <KeepCreatedContext val="N"/>
            </TaskProperties>
            <SIDE_WIN>
              <AllowOptions val="N"/>
              <AllowQuery val="Y"/>
              <AllowModify val="Y"/>
              <AllowCreate val="Y"/>
              <AllowDelete val="Y"/>
              <AllowLocate val="Y"/>
              <AllowRange val="Y"/>
              <AllowIndexChange val="Y"/>
              <AllowSorting val="Y"/>
              <AllowIOFiles val="Y"/>
              <RecordCycle val="Y"/>
              <AllowEvents val="Y"/>
              <AllowIndexOptimization val="Y"/>
              <AllowLocationInQuery val="Y"/>
              <AllowPrintingData val="N"/>
            </SIDE_WIN>
            <WIN>
              <OpenTaskWindow val="N"/>
              <CloseTaskWindow val="Y"/>
              <ForegroundWindow val="Y"/>
              <FlipFld val="N"/>
              <RefreshTaskWindow ReturnValue="N"/>
            </WIN>
            <BOX>
              <Direction val="V"/>
            </BOX>
          </Information>
          <SQL_FORM DB="SourceDB_1_5_1_1" RESTAB="Memory">
            <SQL_STMT_U val=":1,:2,:3,:4,:5,:6,:7,:8,:9,:10,:11,:12,:13,:14,:15,:16,:17,:18,:19,:20,:21,:22,:23,:24"/>
            <INARG>
              <Arguments>
                <Argument>
                  <id val="0"/>
                  <Exp val="2"/>
                </Argument>
                <Argument>
                  <id val="0"/>
                  <Exp val="3"/>
                </Argument>
                <Argument>
                  <id val="0"/>
                  <Exp val="4"/>
                </Argument>
                <Argument>
                  <id val="0"/>
                  <Exp val="5"/>
                </Argument>
                <Argument>
                  <id val="0"/>
                  <Exp val="6"/>
                </Argument>
                <Argument>
                  <id val="0"/>
                  <Exp val="7"/>
                </Argument>
                <Argument>
                  <id val="0"/>
                  <Exp val="8"/>
                </Argument>
                <Argument>
                  <id val="0"/>
                  <Exp val="9"/>
                </Argument>
                <Argument>
                  <id val="0"/>
                  <Exp val="10"/>
                </Argument>
                <Argument>
                  <id val="0"/>
                  <Exp val="11"/>
                </Argument>
                <Argument>
                  <id val="0"/>
                  <Exp val="12"/>
                </Argument>
                <Argument>
                  <id val="0"/>
                  <Exp val="13"/>
                </Argument>
                <Argument>
                  <id val="0"/>
                  <Exp val="14"/>
                </Argument>
                <Argument>
                  <id val="0"/>
                  <Exp val="15"/>
                </Argument>
                <Argument>
                  <id val="0"/>
                  <Exp val="16"/>
                </Argument>
                <Argument>
                  <id val="0"/>
                  <Exp val="17"/>
                </Argument>
                <Argument>
                  <id val="0"/>
                  <Exp val="18"/>
                </Argument>
                <Argument>
                  <id val="0"/>
                  <Exp val="19"/>
                </Argument>
                <Argument>
                  <id val="0"/>
                  <Exp val="20"/>
                </Argument>
                <Argument>
                  <id val="0"/>
                  <Exp val="21"/>
                </Argument>
                <Argument>
                  <id val="0"/>
                  <Exp val="22"/>
                </Argument>
                <Argument>
                  <id val="0"/>
                  <Exp val="23"/>
                </Argument>
                <Argument>
                  <id val="0"/>
                  <Exp val="24"/>
                </Argument>
                <Argument>
                  <id val="0"/>
                  <Exp val="25"/>
                </Argument>
              </Arguments>
            </INARG>
            <OUTARG>
              <Arguments>
                <Argument Var="A"/>
                <Argument Var="B"/>
                <Argument Var="C"/>
                <Argument Var="D"/>
                <Argument Var="E"/>
                <Argument Var="F"/>
                <Argument Var="G"/>
                <Argument Var="H"/>
                <Argument Var="I"/>
                <Argument Var="J"/>
                <Argument Var="K"/>
                <Argument Var="L"/>
                <Argument Var="M"/>
              </Arguments>
            </OUTARG>
          </SQL_FORM>
          <TaskLogic>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="M"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <_TotalVariabls val="26"/>
              <_TotalVirtuals val="26"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <DATAVIEW_SRC Type="Q">
                    <Condition val="N"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </DATAVIEW_SRC>
                </LogicLine>
                <LogicLine>
                  <Select Name="A">
                    <ASS/>
                    <Column val="1"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="B">
                    <ASS/>
                    <Column val="2"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="C">
                    <ASS/>
                    <Column val="3"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="D">
                    <ASS/>
                    <Column val="4"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="E">
                    <ASS/>
                    <Column val="5"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="F">
                    <ASS/>
                    <Column val="6"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="G">
                    <ASS/>
                    <Column val="7"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="H">
                    <ASS/>
                    <Column val="8"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="I">
                    <ASS/>
                    <Column val="9"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="J">
                    <ASS/>
                    <Column val="10"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="K">
                    <ASS/>
                    <Column val="11"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="L">
                    <ASS/>
                    <Column val="12"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="M">
                    <ASS/>
                    <Column val="13"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="N">
                    <ASS/>
                    <Column val="14"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="O">
                    <ASS/>
                    <Column val="15"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="P">
                    <ASS/>
                    <Column val="16"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="Q">
                    <ASS/>
                    <Column val="17"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="R">
                    <ASS/>
                    <Column val="18"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="S">
                    <ASS/>
                    <Column val="19"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="T">
                    <ASS/>
                    <Column val="20"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="U">
                    <ASS/>
                    <Column val="21"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="V">
                    <ASS/>
                    <Column val="22"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="W">
                    <ASS/>
                    <Column val="23"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="X">
                    <ASS/>
                    <Column val="24"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="Y">
                    <ASS/>
                    <Column val="25"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="Z">
                    <ASS/>
                    <Column val="26"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="   ***Begin Source Builder   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="   ***End Source Builder   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=" **** Schema  Destination ****"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="   ***Begin Update Destination Vars   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="N"/>
                    <WithValue val="26"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="27"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="28"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="O"/>
                    <WithValue val="29"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="30"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="P"/>
                    <WithValue val="31"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="32"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="Q"/>
                    <WithValue val="33"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="34"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="R"/>
                    <WithValue val="35"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="36"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="S"/>
                    <WithValue val="37"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="38"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="T"/>
                    <WithValue val="39"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="40"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="U"/>
                    <WithValue val="41"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="42"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="V"/>
                    <WithValue val="43"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="44"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="W"/>
                    <WithValue val="45"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="46"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="X"/>
                    <WithValue val="47"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="48"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="Y"/>
                    <WithValue val="49"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="50"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="Z"/>
                    <WithValue val="51"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="52"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="   ***End Update Destination Vars   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin Destination Builder   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <FormIO>
                    <OperationType val="O"/>
                    <Page val="A"/>
                    <IODeviceInfo>
                      <IoDeviceIndex val="1"/>
                    </IODeviceInfo>
                    <FormEntryInfo>
                      <FormEntryIndex val="2"/>
                    </FormEntryInfo>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </FormIO>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End Destination Builder   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=" Begin Create Titles"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="55"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <FormIO>
                    <OperationType val="O"/>
                    <Page val="A"/>
                    <IODeviceInfo>
                      <IoDeviceIndex val="1"/>
                    </IODeviceInfo>
                    <FormEntryInfo>
                      <FormEntryIndex val="2"/>
                    </FormEntryInfo>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </FormIO>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="56"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=" End Create Titles"/>
                  </Remark>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
          </TaskLogic>
          <TaskForms>
            <FormEntry _last_test_id="1">
              <PropertyList model="FORM_GUI0">
                <Width/>
                <Height/>
                <_Comment/>
                <FormName valUnicode="Empty Program"/>
              </PropertyList>
            </FormEntry>
          </TaskForms>
          <TaskForms>
            <FormEntry CLSS="2" _last_test_id="1">
              <PropertyList model="FORM_TEXT">
                <Width val="382"/>
                <Height val="1"/>
                <_Comment/>
                <FormName valUnicode="FF_Destination_2"/>
              </PropertyList>
              <Control _test_id="1">
                <PropertyList model="CTRL_TEXT_EDIT">
                  <MultiLineEdit/>
                  <Format valUnicode="382"/>
                  <Attribute val="85"/>
                  <Left/>
                  <Width val="382"/>
                  <Height val="1"/>
                  <_Orientation/>
                  <Data Exp="54"/>
                </PropertyList>
              </Control>
            </FormEntry>
          </TaskForms>
          <Expressions>
            <Expression val="1">
              <ExpSyntax val="GetParam('Error')&lt;&gt;0"/>
              <ExpAttribute val="L"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="2">
              <ExpSyntax val="Translatenr('SELECT [FINAL_RESULTS3].[nhk_upper_group_code]')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="3">
              <ExpSyntax val="Translatenr('[FINAL_RESULTS3].[nhk_upper_group_name]')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="4">
              <ExpSyntax val="Translatenr('[FINAL_RESULTS3].[month]')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="5">
              <ExpSyntax val="Translatenr('[FINAL_RESULTS3].[dep_code]')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="6">
              <ExpSyntax val="Translatenr('[FINAL_RESULTS3].[dep_name]')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="7">
              <ExpSyntax val="Translatenr('[FINAL_RESULTS3].[pj_code]')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="8">
              <ExpSyntax val="Translatenr('[FINAL_RESULTS3].[pj_name]')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="9">
              <ExpSyntax val="Translatenr('[FINAL_RESULTS3].[type1_code]')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="10">
              <ExpSyntax val="Translatenr('[FINAL_RESULTS3].[type1_name]')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="11">
              <ExpSyntax val="Translatenr('[FINAL_RESULTS3].[type2_code]')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="12">
              <ExpSyntax val="Translatenr('[FINAL_RESULTS3].[type2_name]')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="13">
              <ExpSyntax val="Translatenr('COUNT( [FINAL_RESULTS3].[emp_code]) AS HEADCOUNT')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="14">
              <ExpSyntax val="Translatenr(' ROUND(SUM([FINAL_RESULTS3].[work_time])')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="15">
              <ExpSyntax val="Translatenr('0) AS TOTAL_TIME FROM dbo.[FINAL_RESULTS3] GROUP BY [FINAL_RESULTS3].[nhk_upper_group_code]')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="16">
              <ExpSyntax val="Translatenr('[FINAL_RESULTS3].[nhk_upper_group_name]')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="17">
              <ExpSyntax val="Translatenr('[FINAL_RESULTS3].[dep_code]')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="18">
              <ExpSyntax val="Translatenr('[FINAL_RESULTS3].[dep_name]')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="19">
              <ExpSyntax val="Translatenr('[FINAL_RESULTS3].[month]')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="20">
              <ExpSyntax val="Translatenr('[FINAL_RESULTS3].[pj_name]')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="21">
              <ExpSyntax val="Translatenr('[FINAL_RESULTS3].[pj_code]')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="22">
              <ExpSyntax val="Translatenr('[FINAL_RESULTS3].[type1_code]')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="23">
              <ExpSyntax val="Translatenr('[FINAL_RESULTS3].[type1_name]')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="24">
              <ExpSyntax val="Translatenr('[FINAL_RESULTS3].[type2_code]')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="25">
              <ExpSyntax val="Translatenr('[FINAL_RESULTS3].[type2_name]')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="26">
              <ExpSyntax val="A"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="27">
              <ExpSyntax val="SetParam('Dest_FF_2',' ')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="28">
              <ExpSyntax val="SetParam('Dest_FF_2',GetParam('Dest_FF_2')&amp;','&amp;rTrim(Astr(N,'30')))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="29">
              <ExpSyntax val="B"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="30">
              <ExpSyntax val="SetParam('Dest_FF_2',GetParam('Dest_FF_2')&amp;','&amp;rTrim(Astr(O,'30')))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="31">
              <ExpSyntax val="C"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="32">
              <ExpSyntax val="SetParam('Dest_FF_2',GetParam('Dest_FF_2')&amp;','&amp;rTrim(Astr(P,'30')))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="33">
              <ExpSyntax val="D"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="34">
              <ExpSyntax val="SetParam('Dest_FF_2',GetParam('Dest_FF_2')&amp;','&amp;rTrim(Astr(Q,'30')))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="35">
              <ExpSyntax val="E"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="36">
              <ExpSyntax val="SetParam('Dest_FF_2',GetParam('Dest_FF_2')&amp;','&amp;rTrim(Astr(R,'30')))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="37">
              <ExpSyntax val="F"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="38">
              <ExpSyntax val="SetParam('Dest_FF_2',GetParam('Dest_FF_2')&amp;','&amp;rTrim(Astr(S,'30')))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="39">
              <ExpSyntax val="G"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="40">
              <ExpSyntax val="SetParam('Dest_FF_2',GetParam('Dest_FF_2')&amp;','&amp;rTrim(Astr(T,'30')))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="41">
              <ExpSyntax val="H"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="42">
              <ExpSyntax val="SetParam('Dest_FF_2',GetParam('Dest_FF_2')&amp;','&amp;rTrim(Astr(U,'30')))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="43">
              <ExpSyntax val="I"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="44">
              <ExpSyntax val="SetParam('Dest_FF_2',GetParam('Dest_FF_2')&amp;','&amp;rTrim(Astr(V,'30')))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="45">
              <ExpSyntax val="J"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="46">
              <ExpSyntax val="SetParam('Dest_FF_2',GetParam('Dest_FF_2')&amp;','&amp;rTrim(Astr(W,'30')))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="47">
              <ExpSyntax val="K"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="48">
              <ExpSyntax val="SetParam('Dest_FF_2',GetParam('Dest_FF_2')&amp;','&amp;rTrim(Astr(X,'30')))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="49">
              <ExpSyntax val="L"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="50">
              <ExpSyntax val="SetParam('Dest_FF_2',GetParam('Dest_FF_2')&amp;','&amp;Trim(str(Y,'12')))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="51">
              <ExpSyntax val="M"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="52">
              <ExpSyntax val="SetParam('Dest_FF_2',GetParam('Dest_FF_2')&amp;','&amp;Trim(str(Z,'12.00')))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="53">
              <ExpSyntax val="TranslateNR(getFullPath(EnvVal ('currentprojectdir') &amp;'Output¥集計用データ出力.csv'))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="54">
              <ExpSyntax val="Del(GetParam('Dest_FF_2'),1,2)"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="55">
              <ExpSyntax val="setparam('Dest_FF_2',' ,所属局コード,所属局名称,対象月,業務実施部局コード,業務実施部局名称,プロジェクトコード,プロジェクト名称,第2階層コード,第2階層名称,第3階層コード,第3階層名称,人数,時間')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="56">
              <ExpSyntax val="setparam('Dest_FF_2',' ')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
          </Expressions>
        </Task>
      </Task>
      <SubTaskNumber/>
    </Programs>
  </ProgramsRepository>
</Application>
